version: '3.8'

services:
  db:
    image: mysql:8
    container_name: pbulle_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pbulle_db
      MYSQL_USER: pbulle_user
      MYSQL_PASSWORD: pbulle_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pbulle_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: pbulle_user
      PMA_PASSWORD: pbulle_password
    ports:
      - '8080:80'

volumes:
  db_data:
